apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-pipeline
spec:
  workspaces:
  - name: s2i-shared-workspace
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks:
    - name: s2i-git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: s2i-shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
    - name: s2i-java
      taskRef:
        name: s2i-java
        kind: ClusterTask
      runAfter:
        - s2i-git-clone
      workspaces:
        - name: source
          workspace: s2i-shared-workspace
      params:
        - name: BUILDER_IMAGE
          value: registry.redhat.io/ubi8/openjdk-11
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(params.IMAGE)
        - name: PATH_CONTEXT
          value: $(params.git-url)
