apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-demo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: deploy
    repoURL: 'https://github.com/junw9293/ocp-demo.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default