apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitclone-build
spec:
  workspaces:
  - name: source
  - name: maven-settings
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: maven-build
    taskRef:
      name: maven
    runAfter:
      - git-clone       
    params:
    - name: GOALS
      value: ["package"]
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: source     
  - name: build-image
    taskRef:
      name: buildah
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: source
    runAfter:
    - maven-build
