---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s2i-source
spec:
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
