apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-spring-demo
spec:
  workspaces:
  - name: source
  - name: maven-settings
  - name: helm-chart
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    type: string
    description: image to be build from the code
  - name: helm-chart-git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: helm-chart-git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"   
  - name: file-path
    type: string
    description: path of values.yaml  
  - name: image-tag
    type: string
    description: image tag to be build from the code             
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: maven-build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - git-clone       
    params:
    - name: GOALS
      value: ["package"]
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: source    
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: source
    runAfter:
    - maven-build 
  - name: yq-and-git-push
    taskRef:
      name: yq-and-git-push
    workspaces:
      - name: output
        workspace: helm-chart
    params:
      - name: file-path
        value: $(params.file-path)
      - name: image-tag
        value: $(params.image-tag)
      - name: helm-chart-git-url
        value: $(params.helm-chart-git-url)  
      - name: helm-chart-git-revision
        value: $(params.helm-chart-git-revision)
    runAfter:
    - build-image          