apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-spring-demo
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: pipeline-spring-demo
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: source
    - name: maven-settings
      configMap:
        name: maven-settings
  params:
    - name: deployment-name
      value: spring-demo
    - name: git-url
      value: https://github.com/joon9293/spring-demo.git 
    - name: git-revision
      value: master
    - name: IMAGE
      value: joon9293/spring-demo