---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bitbucket-push
spec:
  params:
    - name: git-revision
      value: '$(body.changes[0].ref.displayId)'
    - name: gitrepo-url
      value: '$(body.repository.links.clone[1].href)'
    - name: git-repo-name
      value: $(body.repository.name)
    - name: pusher-name
      value: $(body.actor.name)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: bitbucket-template
spec:
  params:
  - name: gitrepo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.git-repo-name)-pipeline-
    spec:
        params:
          - name: URL
            value: $(tt.params.gitrepo-url)
          - name: REVISION
            value: $(tt.params.git-revision)
          - name: S2I_CONTEXT
            value: .
          - name: ARTIFACTS_IMAGE
            value: >-
              image-registry.openshift-image-registry.svc:5000/idmextwin-ci/out-extwin-artifacts:latest
          - name: OUTPUT_IMAGE
            value: 'quay.education.nsw.gov.au/idmextwin/out-extwin:latest'
          - name: S2I_ENV_CONFIGMAP
            value: s2i-environment
          - name: ENV_CONFIGMAP
            value: build-environment
        pipelineRef:
          name: out-extwin-pipeline
        serviceAccountName: pipeline
        workspaces:
          - configMap:
              name: pipeline-ca-trust
            name: trust-store
          - emptyDir: {}
            name: build-cache
          - emptyDir: {}
            name: source

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bitbucket-event-listener
  namespace: idmextwin-ci
  finalizers:
    - eventlisteners.triggers.tekton.dev
  labels:
    argocd.argoproj.io/instance: idmextwin-build
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: bitbucket-push
      interceptors:
        - bitbucket:
            eventTypes:
              - 'repo:refs_changed'
            secretRef:
              secretKey: secretToken
              secretName: bitbucket-webhook-secret
      name: bitbucket-push-trigger
      template:
        ref: bitbucket-template
