apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run
spec:
  pipelineRef:
    name: pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-workspace
    - name: maven-settings
      persistentVolumeClaim:
        claimName: maven-settings
  params:
    - name: deployment-name
      value: spring-demo
    - name: git-url
      value: https://github.com/joon9293/spring-demo.git 
    - name: git-revision
      value: master
    - name: IMAGE
      value: joon9293/spring-demo