apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: s2i-pipeline-run
spec:
  pipelineRef:
    name: s2i-pipeline
  workspaces:
    - name: s2i-shared-workspace
      persistentVolumeClaim:
        claimName: s2i-shared-workspace
    #- name: maven-settings
    #  persistentVolumeClaim:
    #    claimName: maven-settings
  params:
    - name: deployment-name
      value: s2i-demo
    - name: git-url
      value: https://github.com/joon9293/spring-demo.git
    - name: IMAGE
      value: joon9293/spring-demo
