apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: s2i-pipeline-run-spring-demo
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: s2i-pipeline-spring-demo
  workspaces:
    - name: s2i-source
      persistentVolumeClaim:
        claimName: s2i-source
    #- name: maven-settings
    #  persistentVolumeClaim:
    #    claimName: maven-settings
  params:
    - name: deployment-name
      value: s2i-demo
    - name: git-url
      value: https://github.com/junw9293/spring-demo.git
    - name: git-revision
      value: master
    - name: IMAGE
      value: junw9293/spring-demo
