---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source
spec:
  #storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-chart
spec:
  #storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
